import { defineAchievement, achievementId } from "../../types";

export const runningAchievements = [
  defineAchievement({
    id: achievementId("running.first-5k"),
    title: "First 5K",
    description: "Log your first 5K run.",
    category: "running",
    difficulty: "beginner",
    icon: { name: "footprints", library: "lucide" },
    xp: 75,
    prerequisites: [],
    rarity: "common",
    tags: ["distance", "onboarding"],
    requirements: {
      id: "run-count",
      label: "Log 1 run",
      kind: "count",
      metric: "run_count",
      target: 1,
    },
  }),
  defineAchievement({
    id: achievementId("running.sub-25-5k"),
    title: "Sub-25 5K",
    description: "Run a 5K in under 25 minutes.",
    category: "running",
    difficulty: "intermediate",
    icon: { name: "gauge", library: "lucide" },
    xp: 250,
    prerequisites: [achievementId("running.first-5k")],
    rarity: "uncommon",
    tags: ["pace", "race"],
    requirements: {
      id: "five-k-time",
      label: "5K under 25:00",
      kind: "numeric",
      metric: "five_k_time_seconds",
      operator: "lte",
      target: 1500,
    },
  }),
  defineAchievement({
    id: achievementId("running.100km-total"),
    title: "Century Runner",
    description: "Accumulate 100 km of logged running.",
    category: "running",
    difficulty: "advanced",
    icon: { name: "map", library: "lucide" },
    xp: 300,
    prerequisites: [achievementId("running.first-5k")],
    rarity: "rare",
    tags: ["volume", "milestone"],
    requirements: {
      id: "total-distance",
      label: "100 km total",
      kind: "numeric",
      metric: "total_distance_km",
      operator: "gte",
      target: 100,
    },
  }),
] as const;
