import { defineAchievement, achievementId } from "../../types";

export const weightliftingAchievements = [
  defineAchievement({
    id: achievementId("weightlifting.first-session"),
    title: "Platform Ready",
    description: "Log your first weightlifting session.",
    category: "weightlifting",
    difficulty: "beginner",
    icon: { name: "weight", library: "lucide" },
    xp: 50,
    prerequisites: [],
    rarity: "common",
    tags: ["onboarding"],
    requirements: {
      id: "session-count",
      label: "Log 1 session",
      kind: "count",
      metric: "session_count",
      target: 1,
    },
  }),
  defineAchievement({
    id: achievementId("weightlifting.snatch-bodyweight"),
    title: "Bodyweight Snatch",
    description: "Snatch your bodyweight for a 1RM.",
    category: "weightlifting",
    difficulty: "advanced",
    icon: { name: "trophy", library: "lucide" },
    xp: 350,
    prerequisites: [achievementId("weightlifting.first-session")],
    rarity: "rare",
    tags: ["snatch", "strength"],
    requirements: {
      id: "snatch-1rm",
      label: "Snatch 1RM at bodyweight",
      kind: "numeric",
      metric: "snatch_1rm_kg",
      operator: "gte",
      target: 1,
    },
  }),
  defineAchievement({
    id: achievementId("weightlifting.olympic-total-200"),
    title: "200 kg Total",
    description: "Reach a 200 kg snatch + clean & jerk total.",
    category: "weightlifting",
    difficulty: "elite",
    icon: { name: "crown", library: "lucide" },
    xp: 600,
    prerequisites: [achievementId("weightlifting.first-session")],
    rarity: "epic",
    tags: ["total", "competition"],
    requirements: {
      id: "total",
      label: "200 kg Olympic total",
      kind: "numeric",
      metric: "total_kg",
      operator: "gte",
      target: 200,
    },
  }),
] as const;
