import type { CrossfitAchievementSpec } from "../shared";
import { countReq, gteReq, lteReq, streakReq } from "../shared";

export const beginnerSpecs: CrossfitAchievementSpec[] = [
  {
    slug: "first-wod",
    tier: "beginner",
    title: "First WOD",
    description: "Log your first CrossFit workout.",
    icon: "dumbbell",
    xp: 50,
    rarity: "common",
    tags: ["onboarding", "consistency"],
    requirement: countReq("workouts", "Log 1 workout", "workout_count", 1),
  },
  {
    slug: "three-workouts",
    tier: "beginner",
    title: "Three Sessions",
    description: "Complete three logged workouts.",
    icon: "dumbbell",
    xp: 60,
    rarity: "common",
    tags: ["consistency"],
    prerequisiteSlugs: ["first-wod"],
    requirement: countReq("workouts", "Log 3 workouts", "workout_count", 3),
  },
  {
    slug: "five-workouts",
    tier: "beginner",
    title: "Five Sessions",
    description: "Build the habit with five logged workouts.",
    icon: "dumbbell",
    xp: 70,
    rarity: "common",
    tags: ["consistency"],
    prerequisiteSlugs: ["three-workouts"],
    requirement: countReq("workouts", "Log 5 workouts", "workout_count", 5),
  },
  {
    slug: "ten-workouts",
    tier: "beginner",
    title: "Double Digits",
    description: "Log ten CrossFit workouts.",
    icon: "flame",
    xp: 85,
    rarity: "common",
    tags: ["consistency"],
    prerequisiteSlugs: ["five-workouts"],
    requirement: countReq("workouts", "Log 10 workouts", "workout_count", 10),
  },
  {
    slug: "first-benchmark",
    tier: "beginner",
    title: "First Benchmark",
    description: "Log your first named benchmark WOD.",
    icon: "timer",
    xp: 75,
    rarity: "common",
    tags: ["benchmark"],
    prerequisiteSlugs: ["first-wod"],
    requirement: countReq("benchmarks", "Log 1 benchmark", "benchmark_count", 1),
  },
  {
    slug: "first-pull-up",
    tier: "beginner",
    title: "First Pull-up",
    description: "Record your first strict or kipping pull-up.",
    icon: "target",
    xp: 100,
    rarity: "uncommon",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["first-wod"],
    requirement: gteReq("pullups", "1 pull-up", "pullup_max_reps", 1),
  },
  {
    slug: "three-pull-ups",
    tier: "beginner",
    title: "3 Pull-ups",
    description: "Link three pull-ups in a single set.",
    icon: "target",
    xp: 110,
    rarity: "uncommon",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["first-pull-up"],
    requirement: gteReq("pullups", "3 pull-ups", "pullup_max_reps", 3),
  },
  {
    slug: "first-toes-to-bar",
    tier: "beginner",
    title: "First Toes-to-Bar",
    description: "Get your first toes-to-bar rep on the board.",
    icon: "target",
    xp: 100,
    rarity: "uncommon",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["first-wod"],
    requirement: gteReq("ttb", "1 toes-to-bar", "toes_to_bar_max_reps", 1),
  },
  {
    slug: "first-double-under",
    tier: "beginner",
    title: "First Double-under",
    description: "Log your first double-under in a workout.",
    icon: "zap",
    xp: 90,
    rarity: "uncommon",
    tags: ["gymnastics", "engine"],
    prerequisiteSlugs: ["first-wod"],
    requirement: gteReq("du", "1 double-under", "double_under_max_reps", 1),
  },
  {
    slug: "barbell-intro",
    tier: "beginner",
    title: "Barbell Intro",
    description: "Power or squat clean 35 kg in training.",
    icon: "weight",
    xp: 80,
    rarity: "common",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["first-wod"],
    requirement: gteReq("clean", "Clean 35 kg", "clean_1rm_kg", 35),
  },
  {
    slug: "deadlift-61kg",
    tier: "beginner",
    title: "135 lb Deadlift",
    description: "Deadlift 61 kg (135 lb) or more.",
    icon: "weight",
    xp: 95,
    rarity: "uncommon",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["barbell-intro"],
    requirement: gteReq("dl", "Deadlift 61 kg", "deadlift_1rm_kg", 61),
  },
  {
    slug: "back-squat-43kg",
    tier: "beginner",
    title: "95 lb Back Squat",
    description: "Back squat 43 kg (95 lb) or more.",
    icon: "weight",
    xp: 90,
    rarity: "uncommon",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["barbell-intro"],
    requirement: gteReq("sq", "Back squat 43 kg", "back_squat_1rm_kg", 43),
  },
  {
    slug: "shoulder-press-29kg",
    tier: "beginner",
    title: "65 lb Press",
    description: "Strict press 29 kg (65 lb) or more.",
    icon: "weight",
    xp: 85,
    rarity: "common",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["barbell-intro"],
    requirement: gteReq("press", "Press 29 kg", "shoulder_press_1rm_kg", 29),
  },
  {
    slug: "three-day-streak",
    tier: "beginner",
    title: "3-Day Streak",
    description: "Train three days in a row.",
    icon: "flame",
    xp: 80,
    rarity: "common",
    tags: ["consistency", "streak"],
    prerequisiteSlugs: ["first-wod"],
    requirement: streakReq("streak", "3-day streak", 3),
  },
  {
    slug: "cindy-3-rounds",
    tier: "beginner",
    title: "Cindy × 3",
    description: "Complete at least 3 rounds of Cindy in 20 minutes.",
    icon: "timer",
    xp: 90,
    rarity: "common",
    tags: ["benchmark", "engine"],
    prerequisiteSlugs: ["first-benchmark"],
    requirement: gteReq("cindy", "3 Cindy rounds", "cindy_rounds", 3),
  },
  {
    slug: "fifteen-workouts",
    tier: "beginner",
    title: "Fifteen Sessions",
    description: "Log fifteen CrossFit workouts.",
    icon: "dumbbell",
    xp: 100,
    rarity: "common",
    tags: ["consistency"],
    prerequisiteSlugs: ["ten-workouts"],
    requirement: countReq("workouts", "Log 15 workouts", "workout_count", 15),
  },
  {
    slug: "two-benchmarks",
    tier: "beginner",
    title: "Two Benchmarks",
    description: "Log two different benchmark WODs.",
    icon: "timer",
    xp: 95,
    rarity: "uncommon",
    tags: ["benchmark"],
    prerequisiteSlugs: ["first-benchmark"],
    requirement: countReq("benchmarks", "Log 2 benchmarks", "benchmark_count", 2),
  },
  {
    slug: "twenty-workouts",
    tier: "beginner",
    title: "Twenty Sessions",
    description: "Log twenty CrossFit workouts.",
    icon: "flame",
    xp: 110,
    rarity: "uncommon",
    tags: ["consistency"],
    prerequisiteSlugs: ["fifteen-workouts"],
    requirement: countReq("workouts", "Log 20 workouts", "workout_count", 20),
  },
  {
    slug: "five-double-unders",
    tier: "beginner",
    title: "5 Double-unders",
    description: "Link five double-unders unbroken.",
    icon: "zap",
    xp: 100,
    rarity: "uncommon",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["first-double-under"],
    requirement: gteReq("du5", "5 double-unders", "double_under_max_reps", 5),
  },
  {
    slug: "murph-participant",
    tier: "beginner",
    title: "Murph Attempt",
    description: "Finish Murph in any time under 90 minutes.",
    icon: "flag",
    xp: 125,
    rarity: "uncommon",
    tags: ["benchmark", "hero"],
    prerequisiteSlugs: ["ten-workouts"],
    requirement: lteReq("murph", "Murph under 90:00", "murph_time_seconds", 5400),
  },
];
