import type { CrossfitAchievementSpec } from "../shared";
import { countReq, gteReq, lteReq, streakReq } from "../shared";

export const eliteSpecs: CrossfitAchievementSpec[] = [
  {
    slug: "fran-sub-3",
    tier: "elite",
    title: "Sub-3 Fran",
    description: "Complete Fran in under 3 minutes.",
    icon: "timer",
    xp: 650,
    rarity: "epic",
    tags: ["benchmark"],
    prerequisiteSlugs: ["fran-sub-5"],
    requirement: lteReq("fran", "Fran under 3:00", "fran_time_seconds", 180),
  },
  {
    slug: "murph-sub-45",
    tier: "elite",
    title: "Murph Sub-45",
    description: "Complete Murph in under 45 minutes.",
    icon: "flag",
    xp: 600,
    rarity: "epic",
    tags: ["benchmark", "hero"],
    prerequisiteSlugs: ["murph-sub-50"],
    requirement: lteReq("murph", "Murph under 45:00", "murph_time_seconds", 2700),
  },
  {
    slug: "grace-sub-3",
    tier: "elite",
    title: "Grace Sub-3",
    description: "Complete Grace in under 3 minutes.",
    icon: "timer",
    xp: 550,
    rarity: "epic",
    tags: ["benchmark"],
    prerequisiteSlugs: ["grace-sub-4"],
    requirement: lteReq("grace", "Grace under 3:00", "grace_time_seconds", 180),
  },
  {
    slug: "twenty-five-pull-ups",
    tier: "elite",
    title: "25 Pull-ups",
    description: "Complete twenty-five pull-ups in a single set.",
    icon: "target",
    xp: 520,
    rarity: "epic",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["twenty-pull-ups"],
    requirement: gteReq("pullups", "25 pull-ups", "pullup_max_reps", 25),
  },
  {
    slug: "thirty-toes-to-bar",
    tier: "elite",
    title: "30 Toes-to-Bar",
    description: "Link thirty toes-to-bar reps in one set.",
    icon: "target",
    xp: 500,
    rarity: "epic",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["twenty-toes-to-bar"],
    requirement: gteReq("ttb", "30 toes-to-bar", "toes_to_bar_max_reps", 30),
  },
  {
    slug: "hundred-double-unders",
    tier: "elite",
    title: "100 Double-unders",
    description: "Complete one hundred unbroken double-unders.",
    icon: "zap",
    xp: 480,
    rarity: "epic",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["fifty-double-unders"],
    requirement: gteReq("du", "100 double-unders", "double_under_max_reps", 100),
  },
  {
    slug: "clean-120kg",
    tier: "elite",
    title: "120 kg Clean",
    description: "Full clean 120 kg or more.",
    icon: "weight",
    xp: 580,
    rarity: "epic",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["clean-100kg"],
    requirement: gteReq("clean", "Clean 120 kg", "clean_1rm_kg", 120),
  },
  {
    slug: "back-squat-140kg",
    tier: "elite",
    title: "140 kg Back Squat",
    description: "Back squat 140 kg or more.",
    icon: "weight",
    xp: 560,
    rarity: "epic",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["back-squat-100kg"],
    requirement: gteReq("sq", "Back squat 140 kg", "back_squat_1rm_kg", 140),
  },
  {
    slug: "deadlift-180kg",
    tier: "elite",
    title: "180 kg Deadlift",
    description: "Deadlift 180 kg or more.",
    icon: "weight",
    xp: 570,
    rarity: "epic",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["deadlift-140kg"],
    requirement: gteReq("dl", "Deadlift 180 kg", "deadlift_1rm_kg", 180),
  },
  {
    slug: "cindy-20-rounds",
    tier: "elite",
    title: "Cindy × 20",
    description: "Complete twenty rounds of Cindy in 20 minutes.",
    icon: "timer",
    xp: 490,
    rarity: "epic",
    tags: ["benchmark", "engine"],
    prerequisiteSlugs: ["cindy-15-rounds"],
    requirement: gteReq("cindy", "20 Cindy rounds", "cindy_rounds", 20),
  },
  {
    slug: "hundred-fifty-workouts",
    tier: "elite",
    title: "150 Sessions",
    description: "Log one hundred fifty CrossFit workouts.",
    icon: "trophy",
    xp: 520,
    rarity: "epic",
    tags: ["consistency"],
    prerequisiteSlugs: ["hundred-workouts"],
    requirement: countReq("workouts", "Log 150 workouts", "workout_count", 150),
  },
  {
    slug: "twenty-day-streak",
    tier: "elite",
    title: "20-Day Streak",
    description: "Train twenty consecutive days.",
    icon: "flame",
    xp: 510,
    rarity: "epic",
    tags: ["consistency", "streak"],
    prerequisiteSlugs: ["fourteen-day-streak"],
    requirement: streakReq("streak", "20-day streak", 20),
  },
  {
    slug: "engine-seventy-five",
    tier: "elite",
    title: "Engine 75",
    description: "Reach an engine score of 75 or higher.",
    icon: "gauge",
    xp: 480,
    rarity: "epic",
    tags: ["engine"],
    prerequisiteSlugs: ["engine-fifty"],
    requirement: gteReq("engine", "Engine score 75", "engine_score", 75),
  },
  {
    slug: "overall-seventy",
    tier: "elite",
    title: "Athlete Score 70",
    description: "Reach an overall athlete score of 70 or higher.",
    icon: "gauge",
    xp: 500,
    rarity: "epic",
    tags: ["scoring"],
    prerequisiteSlugs: ["hundred-workouts"],
    requirement: gteReq("overall", "Overall score 70", "overall_score", 70),
  },
  {
    slug: "ten-muscle-ups",
    tier: "elite",
    title: "10 Muscle-ups",
    description: "Complete ten muscle-ups in a single set.",
    icon: "target",
    xp: 590,
    rarity: "epic",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["five-muscle-ups"],
    requirement: gteReq("mu", "10 muscle-ups", "muscle_up_max_reps", 10),
  },
  {
    slug: "isabel-sub-3-30",
    tier: "elite",
    title: "Isabel Sub-3:30",
    description: "Complete Isabel in under 3 minutes 30 seconds.",
    icon: "timer",
    xp: 470,
    rarity: "epic",
    tags: ["benchmark"],
    prerequisiteSlugs: ["isabel-sub-6"],
    requirement: lteReq("isabel", "Isabel under 3:30", "isabel_time_seconds", 210),
  },
  {
    slug: "helen-sub-10",
    tier: "elite",
    title: "Helen Sub-10",
    description: "Complete Helen in under 10 minutes.",
    icon: "timer",
    xp: 485,
    rarity: "epic",
    tags: ["benchmark"],
    prerequisiteSlugs: ["helen-sub-12"],
    requirement: lteReq("helen", "Helen under 10:00", "helen_time_seconds", 600),
  },
  {
    slug: "competition-finisher",
    tier: "elite",
    title: "Competition Finisher",
    description: "Enter and complete a CrossFit competition.",
    icon: "medal",
    xp: 540,
    rarity: "epic",
    tags: ["competition"],
    prerequisiteSlugs: ["hundred-workouts"],
    requirement: countReq("comp", "1 competition", "competition_count", 1),
  },
  {
    slug: "twenty-benchmarks",
    tier: "elite",
    title: "Twenty Benchmarks",
    description: "Log twenty different benchmark WODs.",
    icon: "timer",
    xp: 530,
    rarity: "epic",
    tags: ["benchmark"],
    prerequisiteSlugs: ["ten-benchmarks"],
    requirement: countReq("benchmarks", "Log 20 benchmarks", "benchmark_count", 20),
  },
  {
    slug: "first-hspu",
    tier: "elite",
    title: "First HSPU",
    description: "Record your first strict handstand push-up.",
    icon: "target",
    xp: 460,
    rarity: "epic",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["ten-pull-ups"],
    requirement: gteReq("hspu", "1 handstand push-up", "handstand_pushup_max_reps", 1),
  },
];
