import type { CrossfitAchievementSpec } from "../shared";
import { countReq, gteReq, lteReq, streakReq } from "../shared";

export const intermediateSpecs: CrossfitAchievementSpec[] = [
  {
    slug: "five-pull-ups",
    tier: "intermediate",
    title: "5 Pull-ups",
    description: "Complete five pull-ups in a single set.",
    icon: "target",
    xp: 140,
    rarity: "uncommon",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["three-pull-ups"],
    requirement: gteReq("pullups", "5 pull-ups", "pullup_max_reps", 5),
  },
  {
    slug: "ten-pull-ups",
    tier: "intermediate",
    title: "10 Pull-ups",
    description: "Complete ten pull-ups in a single set.",
    icon: "target",
    xp: 175,
    rarity: "uncommon",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["five-pull-ups"],
    requirement: gteReq("pullups", "10 pull-ups", "pullup_max_reps", 10),
  },
  {
    slug: "five-toes-to-bar",
    tier: "intermediate",
    title: "5 Toes-to-Bar",
    description: "Link five toes-to-bar reps unbroken.",
    icon: "target",
    xp: 150,
    rarity: "uncommon",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["first-toes-to-bar"],
    requirement: gteReq("ttb", "5 toes-to-bar", "toes_to_bar_max_reps", 5),
  },
  {
    slug: "ten-toes-to-bar",
    tier: "intermediate",
    title: "10 Toes-to-Bar",
    description: "Link ten toes-to-bar reps in one set.",
    icon: "target",
    xp: 185,
    rarity: "rare",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["five-toes-to-bar"],
    requirement: gteReq("ttb", "10 toes-to-bar", "toes_to_bar_max_reps", 10),
  },
  {
    slug: "twenty-double-unders",
    tier: "intermediate",
    title: "20 Double-unders",
    description: "Complete twenty unbroken double-unders.",
    icon: "zap",
    xp: 150,
    rarity: "uncommon",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["five-double-unders"],
    requirement: gteReq("du", "20 double-unders", "double_under_max_reps", 20),
  },
  {
    slug: "seven-day-streak",
    tier: "intermediate",
    title: "7-Day Streak",
    description: "Train at least once per day for seven consecutive days.",
    icon: "flame",
    xp: 160,
    rarity: "uncommon",
    tags: ["consistency", "streak"],
    prerequisiteSlugs: ["three-day-streak"],
    requirement: streakReq("streak", "7-day streak", 7),
  },
  {
    slug: "thirty-workouts",
    tier: "intermediate",
    title: "Thirty Sessions",
    description: "Log thirty CrossFit workouts.",
    icon: "dumbbell",
    xp: 150,
    rarity: "uncommon",
    tags: ["consistency"],
    prerequisiteSlugs: ["twenty-workouts"],
    requirement: countReq("workouts", "Log 30 workouts", "workout_count", 30),
  },
  {
    slug: "clean-61kg",
    tier: "intermediate",
    title: "135 lb Clean",
    description: "Full clean 61 kg (135 lb) or more.",
    icon: "weight",
    xp: 165,
    rarity: "uncommon",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["barbell-intro"],
    requirement: gteReq("clean", "Clean 61 kg", "clean_1rm_kg", 61),
  },
  {
    slug: "clean-84kg",
    tier: "intermediate",
    title: "185 lb Clean",
    description: "Full clean 84 kg (185 lb) or more.",
    icon: "weight",
    xp: 200,
    rarity: "rare",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["clean-61kg"],
    requirement: gteReq("clean", "Clean 84 kg", "clean_1rm_kg", 84),
  },
  {
    slug: "back-squat-84kg",
    tier: "intermediate",
    title: "185 lb Back Squat",
    description: "Back squat 84 kg (185 lb) or more.",
    icon: "weight",
    xp: 190,
    rarity: "rare",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["back-squat-43kg"],
    requirement: gteReq("sq", "Back squat 84 kg", "back_squat_1rm_kg", 84),
  },
  {
    slug: "deadlift-102kg",
    tier: "intermediate",
    title: "225 lb Deadlift",
    description: "Deadlift 102 kg (225 lb) or more.",
    icon: "weight",
    xp: 195,
    rarity: "rare",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["deadlift-61kg"],
    requirement: gteReq("dl", "Deadlift 102 kg", "deadlift_1rm_kg", 102),
  },
  {
    slug: "fran-sub-10",
    tier: "intermediate",
    title: "Fran Sub-10",
    description: "Complete Fran in under 10 minutes.",
    icon: "timer",
    xp: 200,
    rarity: "rare",
    tags: ["benchmark"],
    prerequisiteSlugs: ["first-benchmark"],
    requirement: lteReq("fran", "Fran under 10:00", "fran_time_seconds", 600),
  },
  {
    slug: "grace-sub-6",
    tier: "intermediate",
    title: "Grace Sub-6",
    description: "Complete Grace in under 6 minutes.",
    icon: "timer",
    xp: 185,
    rarity: "rare",
    tags: ["benchmark"],
    prerequisiteSlugs: ["first-benchmark"],
    requirement: lteReq("grace", "Grace under 6:00", "grace_time_seconds", 360),
  },
  {
    slug: "five-benchmarks",
    tier: "intermediate",
    title: "Five Benchmarks",
    description: "Log five different benchmark WODs.",
    icon: "timer",
    xp: 175,
    rarity: "uncommon",
    tags: ["benchmark"],
    prerequisiteSlugs: ["two-benchmarks"],
    requirement: countReq("benchmarks", "Log 5 benchmarks", "benchmark_count", 5),
  },
  {
    slug: "murph-finish",
    tier: "intermediate",
    title: "Murph Finish",
    description: "Complete Murph in under 80 minutes.",
    icon: "flag",
    xp: 220,
    rarity: "rare",
    tags: ["benchmark", "hero"],
    prerequisiteSlugs: ["murph-participant"],
    requirement: lteReq("murph", "Murph under 80:00", "murph_time_seconds", 4800),
  },
  {
    slug: "cindy-10-rounds",
    tier: "intermediate",
    title: "Cindy × 10",
    description: "Complete ten rounds of Cindy in 20 minutes.",
    icon: "timer",
    xp: 190,
    rarity: "rare",
    tags: ["benchmark", "engine"],
    prerequisiteSlugs: ["cindy-3-rounds"],
    requirement: gteReq("cindy", "10 Cindy rounds", "cindy_rounds", 10),
  },
  {
    slug: "forty-workouts",
    tier: "intermediate",
    title: "Forty Sessions",
    description: "Log forty CrossFit workouts.",
    icon: "dumbbell",
    xp: 170,
    rarity: "uncommon",
    tags: ["consistency"],
    prerequisiteSlugs: ["thirty-workouts"],
    requirement: countReq("workouts", "Log 40 workouts", "workout_count", 40),
  },
  {
    slug: "first-muscle-up",
    tier: "intermediate",
    title: "First Muscle-up",
    description: "Record your first bar or ring muscle-up.",
    icon: "target",
    xp: 225,
    rarity: "rare",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["ten-pull-ups"],
    requirement: gteReq("mu", "1 muscle-up", "muscle_up_max_reps", 1),
  },
  {
    slug: "engine-fifty",
    tier: "intermediate",
    title: "Engine 50",
    description: "Reach an engine score of 50 or higher.",
    icon: "gauge",
    xp: 180,
    rarity: "uncommon",
    tags: ["engine"],
    prerequisiteSlugs: ["twenty-workouts"],
    requirement: gteReq("engine", "Engine score 50", "engine_score", 50),
  },
  {
    slug: "isabel-sub-6",
    tier: "intermediate",
    title: "Isabel Sub-6",
    description: "Complete Isabel (30 snatches) in under 6 minutes.",
    icon: "timer",
    xp: 195,
    rarity: "rare",
    tags: ["benchmark"],
    prerequisiteSlugs: ["first-benchmark"],
    requirement: lteReq("isabel", "Isabel under 6:00", "isabel_time_seconds", 360),
  },
];
