import type { CrossfitAchievementSpec } from "../shared";
import { boolReq, countReq, gteReq, lteReq, streakReq } from "../shared";

export const legendarySpecs: CrossfitAchievementSpec[] = [
  {
    slug: "fran-sub-2-30",
    tier: "legendary",
    title: "Sub-2:30 Fran",
    description: "Complete Fran in under 2 minutes 30 seconds.",
    icon: "crown",
    xp: 1100,
    rarity: "legendary",
    tags: ["benchmark"],
    prerequisiteSlugs: ["fran-sub-3"],
    requirement: lteReq("fran", "Fran under 2:30", "fran_time_seconds", 150),
  },
  {
    slug: "murph-sub-40",
    tier: "legendary",
    title: "Murph Sub-40",
    description: "Complete Murph in under 40 minutes.",
    icon: "flag",
    xp: 1000,
    rarity: "legendary",
    tags: ["benchmark", "hero"],
    prerequisiteSlugs: ["murph-sub-45"],
    requirement: lteReq("murph", "Murph under 40:00", "murph_time_seconds", 2400),
  },
  {
    slug: "grace-sub-90",
    tier: "legendary",
    title: "Grace Sub-1:30",
    description: "Complete Grace in under 90 seconds.",
    icon: "timer",
    xp: 950,
    rarity: "legendary",
    tags: ["benchmark"],
    prerequisiteSlugs: ["grace-sub-3"],
    requirement: lteReq("grace", "Grace under 1:30", "grace_time_seconds", 90),
  },
  {
    slug: "thirty-pull-ups",
    tier: "legendary",
    title: "30 Pull-ups",
    description: "Complete thirty pull-ups in a single set.",
    icon: "target",
    xp: 900,
    rarity: "legendary",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["twenty-five-pull-ups"],
    requirement: gteReq("pullups", "30 pull-ups", "pullup_max_reps", 30),
  },
  {
    slug: "twenty-muscle-ups",
    tier: "legendary",
    title: "20 Muscle-ups",
    description: "Complete twenty muscle-ups in a single set.",
    icon: "target",
    xp: 1050,
    rarity: "legendary",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["ten-muscle-ups"],
    requirement: gteReq("mu", "20 muscle-ups", "muscle_up_max_reps", 20),
  },
  {
    slug: "two-hundred-double-unders",
    tier: "legendary",
    title: "200 Double-unders",
    description: "Complete two hundred unbroken double-unders.",
    icon: "zap",
    xp: 850,
    rarity: "legendary",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["hundred-double-unders"],
    requirement: gteReq("du", "200 double-unders", "double_under_max_reps", 200),
  },
  {
    slug: "clean-140kg",
    tier: "legendary",
    title: "140 kg Clean",
    description: "Full clean 140 kg or more.",
    icon: "weight",
    xp: 980,
    rarity: "legendary",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["clean-120kg"],
    requirement: gteReq("clean", "Clean 140 kg", "clean_1rm_kg", 140),
  },
  {
    slug: "back-squat-160kg",
    tier: "legendary",
    title: "160 kg Back Squat",
    description: "Back squat 160 kg or more.",
    icon: "weight",
    xp: 960,
    rarity: "legendary",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["back-squat-140kg"],
    requirement: gteReq("sq", "Back squat 160 kg", "back_squat_1rm_kg", 160),
  },
  {
    slug: "deadlift-220kg",
    tier: "legendary",
    title: "220 kg Deadlift",
    description: "Deadlift 220 kg or more.",
    icon: "weight",
    xp: 970,
    rarity: "legendary",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["deadlift-180kg"],
    requirement: gteReq("dl", "Deadlift 220 kg", "deadlift_1rm_kg", 220),
  },
  {
    slug: "quarterfinal-qualification",
    tier: "legendary",
    title: "Quarterfinal Qualification",
    description: "Qualify for the CrossFit Games Quarterfinals.",
    icon: "crown",
    xp: 1200,
    rarity: "legendary",
    tags: ["competition"],
    prerequisiteSlugs: ["competition-finisher"],
    requirement: boolReq("qf", "Quarterfinal qualifier", "quarterfinal_qualified"),
  },
  {
    slug: "two-hundred-workouts",
    tier: "legendary",
    title: "200 Sessions",
    description: "Log two hundred CrossFit workouts.",
    icon: "trophy",
    xp: 880,
    rarity: "legendary",
    tags: ["consistency"],
    prerequisiteSlugs: ["hundred-fifty-workouts"],
    requirement: countReq("workouts", "Log 200 workouts", "workout_count", 200),
  },
  {
    slug: "thirty-day-streak",
    tier: "legendary",
    title: "30-Day Streak",
    description: "Train thirty consecutive days.",
    icon: "flame",
    xp: 920,
    rarity: "legendary",
    tags: ["consistency", "streak"],
    prerequisiteSlugs: ["twenty-day-streak"],
    requirement: streakReq("streak", "30-day streak", 30),
  },
  {
    slug: "engine-ninety",
    tier: "legendary",
    title: "Engine 90",
    description: "Reach an engine score of 90 or higher.",
    icon: "gauge",
    xp: 860,
    rarity: "legendary",
    tags: ["engine"],
    prerequisiteSlugs: ["engine-seventy-five"],
    requirement: gteReq("engine", "Engine score 90", "engine_score", 90),
  },
  {
    slug: "overall-eighty-five",
    tier: "legendary",
    title: "Athlete Score 85",
    description: "Reach an overall athlete score of 85 or higher.",
    icon: "gauge",
    xp: 900,
    rarity: "legendary",
    tags: ["scoring"],
    prerequisiteSlugs: ["overall-seventy"],
    requirement: gteReq("overall", "Overall score 85", "overall_score", 85),
  },
  {
    slug: "cindy-25-rounds",
    tier: "legendary",
    title: "Cindy × 25",
    description: "Complete twenty-five rounds of Cindy in 20 minutes.",
    icon: "timer",
    xp: 870,
    rarity: "legendary",
    tags: ["benchmark", "engine"],
    prerequisiteSlugs: ["cindy-20-rounds"],
    requirement: gteReq("cindy", "25 Cindy rounds", "cindy_rounds", 25),
  },
  {
    slug: "fifty-benchmarks",
    tier: "legendary",
    title: "Fifty Benchmarks",
    description: "Log fifty different benchmark WODs.",
    icon: "timer",
    xp: 940,
    rarity: "legendary",
    tags: ["benchmark"],
    prerequisiteSlugs: ["twenty-benchmarks"],
    requirement: countReq("benchmarks", "Log 50 benchmarks", "benchmark_count", 50),
  },
  {
    slug: "helen-sub-8",
    tier: "legendary",
    title: "Helen Sub-8",
    description: "Complete Helen in under 8 minutes.",
    icon: "timer",
    xp: 890,
    rarity: "legendary",
    tags: ["benchmark"],
    prerequisiteSlugs: ["helen-sub-10"],
    requirement: lteReq("helen", "Helen under 8:00", "helen_time_seconds", 480),
  },
  {
    slug: "isabel-sub-2-30",
    tier: "legendary",
    title: "Isabel Sub-2:30",
    description: "Complete Isabel in under 2 minutes 30 seconds.",
    icon: "timer",
    xp: 910,
    rarity: "legendary",
    tags: ["benchmark"],
    prerequisiteSlugs: ["isabel-sub-3-30"],
    requirement: lteReq("isabel", "Isabel under 2:30", "isabel_time_seconds", 150),
  },
  {
    slug: "five-hundred-workouts",
    tier: "legendary",
    title: "500 Sessions",
    description: "Log five hundred CrossFit workouts — a career of training.",
    icon: "trophy",
    xp: 1150,
    rarity: "legendary",
    tags: ["consistency"],
    prerequisiteSlugs: ["two-hundred-workouts"],
    requirement: countReq("workouts", "Log 500 workouts", "workout_count", 500),
  },
  {
    slug: "ascendant",
    tier: "legendary",
    title: "Ascendant",
    description: "Reach an overall athlete score of 90 — elite across all domains.",
    icon: "crown",
    xp: 1200,
    rarity: "legendary",
    tags: ["scoring"],
    prerequisiteSlugs: ["overall-eighty-five"],
    requirement: gteReq("overall", "Overall score 90", "overall_score", 90),
  },
];
