import type { CrossfitAchievementSpec } from "../shared";
import { countReq, gteReq, lteReq, streakReq } from "../shared";

/** RX tier — stored as `advanced` difficulty with `rx` tag. */
export const rxSpecs: CrossfitAchievementSpec[] = [
  {
    slug: "fifteen-pull-ups",
    tier: "advanced",
    title: "15 Pull-ups",
    description: "Complete fifteen pull-ups in a single set.",
    icon: "target",
    xp: 280,
    rarity: "rare",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["ten-pull-ups"],
    requirement: gteReq("pullups", "15 pull-ups", "pullup_max_reps", 15),
  },
  {
    slug: "twenty-pull-ups",
    tier: "advanced",
    title: "20 Pull-ups",
    description: "Complete twenty pull-ups in a single set.",
    icon: "target",
    xp: 320,
    rarity: "rare",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["fifteen-pull-ups"],
    requirement: gteReq("pullups", "20 pull-ups", "pullup_max_reps", 20),
  },
  {
    slug: "twenty-toes-to-bar",
    tier: "advanced",
    title: "20 Toes-to-Bar",
    description: "Link twenty toes-to-bar reps in one set.",
    icon: "target",
    xp: 300,
    rarity: "rare",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["ten-toes-to-bar"],
    requirement: gteReq("ttb", "20 toes-to-bar", "toes_to_bar_max_reps", 20),
  },
  {
    slug: "fifty-double-unders",
    tier: "advanced",
    title: "50 Double-unders",
    description: "Complete fifty unbroken double-unders.",
    icon: "zap",
    xp: 290,
    rarity: "rare",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["twenty-double-unders"],
    requirement: gteReq("du", "50 double-unders", "double_under_max_reps", 50),
  },
  {
    slug: "clean-100kg",
    tier: "advanced",
    title: "100 kg Clean",
    description: "Full clean 100 kg or more.",
    icon: "weight",
    xp: 350,
    rarity: "rare",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["clean-84kg"],
    requirement: gteReq("clean", "Clean 100 kg", "clean_1rm_kg", 100),
  },
  {
    slug: "back-squat-100kg",
    tier: "advanced",
    title: "100 kg Back Squat",
    description: "Back squat 100 kg or more.",
    icon: "weight",
    xp: 340,
    rarity: "rare",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["back-squat-84kg"],
    requirement: gteReq("sq", "Back squat 100 kg", "back_squat_1rm_kg", 100),
  },
  {
    slug: "bodyweight-back-squat",
    tier: "advanced",
    title: "Bodyweight Back Squat",
    description: "Back squat at or above your bodyweight (1.0× BW ratio).",
    icon: "weight",
    xp: 360,
    rarity: "epic",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["back-squat-100kg"],
    requirement: gteReq("bw-sq", "1.0× bodyweight squat", "back_squat_bodyweight_ratio", 1),
  },
  {
    slug: "deadlift-140kg",
    tier: "advanced",
    title: "140 kg Deadlift",
    description: "Deadlift 140 kg or more.",
    icon: "weight",
    xp: 330,
    rarity: "rare",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["deadlift-102kg"],
    requirement: gteReq("dl", "Deadlift 140 kg", "deadlift_1rm_kg", 140),
  },
  {
    slug: "fran-sub-5",
    tier: "advanced",
    title: "Fran Sub-5",
    description: "Complete Fran in under 5 minutes.",
    icon: "timer",
    xp: 380,
    rarity: "epic",
    tags: ["benchmark"],
    prerequisiteSlugs: ["fran-sub-10"],
    requirement: lteReq("fran", "Fran under 5:00", "fran_time_seconds", 300),
  },
  {
    slug: "murph-sub-50",
    tier: "advanced",
    title: "Murph Sub-50",
    description: "Complete Murph in under 50 minutes.",
    icon: "flag",
    xp: 370,
    rarity: "epic",
    tags: ["benchmark", "hero"],
    prerequisiteSlugs: ["murph-finish"],
    requirement: lteReq("murph", "Murph under 50:00", "murph_time_seconds", 3000),
  },
  {
    slug: "grace-sub-4",
    tier: "advanced",
    title: "Grace Sub-4",
    description: "Complete Grace in under 4 minutes.",
    icon: "timer",
    xp: 340,
    rarity: "rare",
    tags: ["benchmark"],
    prerequisiteSlugs: ["grace-sub-6"],
    requirement: lteReq("grace", "Grace under 4:00", "grace_time_seconds", 240),
  },
  {
    slug: "helen-sub-12",
    tier: "advanced",
    title: "Helen Sub-12",
    description: "Complete Helen in under 12 minutes.",
    icon: "timer",
    xp: 335,
    rarity: "rare",
    tags: ["benchmark"],
    prerequisiteSlugs: ["first-benchmark"],
    requirement: lteReq("helen", "Helen under 12:00", "helen_time_seconds", 720),
  },
  {
    slug: "cindy-15-rounds",
    tier: "advanced",
    title: "Cindy × 15",
    description: "Complete fifteen rounds of Cindy in 20 minutes.",
    icon: "timer",
    xp: 325,
    rarity: "rare",
    tags: ["benchmark", "engine"],
    prerequisiteSlugs: ["cindy-10-rounds"],
    requirement: gteReq("cindy", "15 Cindy rounds", "cindy_rounds", 15),
  },
  {
    slug: "seventy-five-workouts",
    tier: "advanced",
    title: "75 Sessions",
    description: "Log seventy-five CrossFit workouts.",
    icon: "dumbbell",
    xp: 300,
    rarity: "rare",
    tags: ["consistency"],
    prerequisiteSlugs: ["forty-workouts"],
    requirement: countReq("workouts", "Log 75 workouts", "workout_count", 75),
  },
  {
    slug: "hundred-workouts",
    tier: "advanced",
    title: "100 Sessions",
    description: "Log one hundred CrossFit workouts.",
    icon: "trophy",
    xp: 400,
    rarity: "epic",
    tags: ["consistency"],
    prerequisiteSlugs: ["seventy-five-workouts"],
    requirement: countReq("workouts", "Log 100 workouts", "workout_count", 100),
  },
  {
    slug: "ten-benchmarks",
    tier: "advanced",
    title: "Ten Benchmarks",
    description: "Log ten different benchmark WODs.",
    icon: "timer",
    xp: 310,
    rarity: "rare",
    tags: ["benchmark"],
    prerequisiteSlugs: ["five-benchmarks"],
    requirement: countReq("benchmarks", "Log 10 benchmarks", "benchmark_count", 10),
  },
  {
    slug: "fourteen-day-streak",
    tier: "advanced",
    title: "14-Day Streak",
    description: "Train fourteen consecutive days.",
    icon: "flame",
    xp: 315,
    rarity: "rare",
    tags: ["consistency", "streak"],
    prerequisiteSlugs: ["seven-day-streak"],
    requirement: streakReq("streak", "14-day streak", 14),
  },
  {
    slug: "thruster-61kg",
    tier: "advanced",
    title: "135 lb Thruster",
    description: "Thruster 61 kg (135 lb) or more.",
    icon: "weight",
    xp: 305,
    rarity: "rare",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["clean-61kg"],
    requirement: gteReq("thruster", "Thruster 61 kg", "thruster_1rm_kg", 61),
  },
  {
    slug: "five-muscle-ups",
    tier: "advanced",
    title: "5 Muscle-ups",
    description: "Complete five muscle-ups in a single set.",
    icon: "target",
    xp: 360,
    rarity: "epic",
    tags: ["gymnastics"],
    prerequisiteSlugs: ["first-muscle-up"],
    requirement: gteReq("mu", "5 muscle-ups", "muscle_up_max_reps", 5),
  },
  {
    slug: "power-clean-100kg",
    tier: "advanced",
    title: "100 kg Power Clean",
    description: "Power clean 100 kg or more.",
    icon: "weight",
    xp: 345,
    rarity: "rare",
    tags: ["weightlifting"],
    prerequisiteSlugs: ["clean-100kg"],
    requirement: gteReq("pc", "Power clean 100 kg", "power_clean_1rm_kg", 100),
  },
];
