import type { CrossfitAchievementSpec } from "../shared";
import { gteReq } from "../shared";

/** Linear skill-tree achievements — prerequisites form the chain automatically. */
export const skillTreeSpecs: CrossfitAchievementSpec[] = [
  {
    slug: "strict-pull-up",
    tier: "beginner",
    title: "Strict Pull-up",
    description: "Record your first strict pull-up — the foundation of the gymnastics pull chain.",
    icon: "target",
    xp: 100,
    rarity: "common",
    tags: ["skill-tree", "gymnastics-pull"],
    requirement: gteReq("strict-pull", "1 strict pull-up", "strict_pullup_max_reps", 1),
  },
  {
    slug: "chest-to-bar",
    tier: "intermediate",
    title: "Chest-to-Bar",
    description: "Link your first chest-to-bar pull-up with control.",
    icon: "activity",
    xp: 160,
    rarity: "uncommon",
    tags: ["skill-tree", "gymnastics-pull"],
    prerequisiteSlugs: ["strict-pull-up"],
    requirement: gteReq("ctb", "1 chest-to-bar", "ctb_max_reps", 1),
  },
  {
    slug: "bar-muscle-up",
    tier: "intermediate",
    title: "Bar Muscle-up",
    description: "Get your first bar muscle-up over the bar.",
    icon: "dumbbell",
    xp: 220,
    rarity: "rare",
    tags: ["skill-tree", "gymnastics-pull"],
    prerequisiteSlugs: ["chest-to-bar"],
    requirement: gteReq("bmu", "1 bar muscle-up", "bar_muscle_up_max_reps", 1),
  },
  {
    slug: "ring-muscle-up",
    tier: "advanced",
    title: "Ring Muscle-up",
    description: "Transition to rings with your first ring muscle-up.",
    icon: "trophy",
    xp: 300,
    rarity: "epic",
    tags: ["skill-tree", "gymnastics-pull"],
    prerequisiteSlugs: ["bar-muscle-up"],
    requirement: gteReq("rmu", "1 ring muscle-up", "ring_muscle_up_max_reps", 1),
  },
  {
    slug: "thirty-unbroken-pullups",
    tier: "elite",
    title: "30 Unbroken",
    description: "Complete thirty pull-ups in a single unbroken set.",
    icon: "flame",
    xp: 450,
    rarity: "epic",
    tags: ["skill-tree", "gymnastics-pull"],
    prerequisiteSlugs: ["ring-muscle-up"],
    requirement: gteReq("30-unbroken", "30 unbroken pull-ups", "pullup_max_reps", 30),
  },
  {
    slug: "fifty-unbroken-pullups",
    tier: "legendary",
    title: "50 Unbroken",
    description: "Fifty pull-ups without breaking — elite gymnastics endurance.",
    icon: "crown",
    xp: 700,
    rarity: "legendary",
    tags: ["skill-tree", "gymnastics-pull"],
    prerequisiteSlugs: ["thirty-unbroken-pullups"],
    requirement: gteReq("50-unbroken", "50 unbroken pull-ups", "pullup_max_reps", 50),
  },
];
